# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-type: 'all'
    open-pull-requests-limit: 99
    groups:
      angular-version-updates:
        applies-to: version-updates
        patterns:
          - '@angular*'
          - 'ngx*'
        update-types:
          - 'minor'
          - 'patch'
      angular-security-updates:
        applies-to: security-updates
        patterns:
          - '@angular*'
          - 'ngx*'
        update-types:
          - 'patch'
          - 'minor'
      production-version-updates:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - 'patch'
          - 'minor'
      production-security-updates:
        applies-to: security-updates
        dependency-type: production
        update-types:
          - 'patch'
          - 'minor'
      development-version-updates:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - 'patch'
          - 'minor'
      development-security-updates:
        applies-to: security-updates
        dependency-type: development
        update-types:
          - 'patch'
          - 'minor'
    ignore:
      - dependency-name: '@angular*'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/iframe-resizer'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
      - dependency-name: 'cypress'
        update-types: ['version-update:semver-major']
      - dependency-name: '*eslint*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'iframe-resizer'
        update-types: ['version-update:semver-major']
      - dependency-name: 'ngx*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'zone.js'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
