name: update-angular-major-version
on:
  schedule:
    - cron: '0 0 * * 0' # every sunday at midnight
  workflow_dispatch:
env:
  DEPENDENCY_NAME: 'angular-eslint'
permissions: write-all
jobs:
  update-angular-major-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm install -g latest-version
      - name: Parse package-lock.json and check for new version
        id: check-version
        run: |
          CURRENT_VERSION=$(jq -r ".packages[\"node_modules/$DEPENDENCY_NAME\"].version" package-lock.json)
          echo "Current version of $DEPENDENCY_NAME: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"
          LATEST_VERSION=$(npx --yes latest-version-cli "$DEPENDENCY_NAME")
          echo "Latest version of $DEPENDENCY_NAME: $LATEST_VERSION"
          echo "LATEST_VERSION=$LATEST_VERSION" >> "$GITHUB_OUTPUT"

          CURRENT_MAJOR_VERSION=$(echo "$CURRENT_VERSION" | cut -d'.' -f1)
          echo "Current major version of $DEPENDENCY_NAME: $CURRENT_MAJOR_VERSION"
          echo "CURRENT_MAJOR_VERSION=$CURRENT_MAJOR_VERSION" >> "$GITHUB_OUTPUT"
          LATEST_MAJOR_VERSION=$(echo "$LATEST_VERSION" | cut -d'.' -f1)
          echo "Latest major version of $DEPENDENCY_NAME: $LATEST_MAJOR_VERSION"
          echo "LATEST_MAJOR_VERSION=$LATEST_MAJOR_VERSION" >> "$GITHUB_OUTPUT"

          if [ "$CURRENT_MAJOR_VERSION" != "$LATEST_MAJOR_VERSION" ]; then
            echo "There is a new version of $DEPENDENCY_NAME available!"
            echo "BRANCH_NAME=upgrade-from-angular-$CURRENT_MAJOR_VERSION-to-angular-$LATEST_MAJOR_VERSION" >> "$GITHUB_OUTPUT"
          else
            echo "You are using the latest version of $DEPENDENCY_NAME."
            echo "BRANCH_NAME=na" >> "$GITHUB_OUTPUT"
          fi
      - name: Check if BRANCH_NAME exists
        id: check-branch
        if: steps.check-version.outputs.BRANCH_NAME != 'na'
        env:
          BRANCH_NAME: ${{ steps.check-version.outputs.BRANCH_NAME }}
          CURRENT_VERSION: ${{ steps.check-version.outputs.CURRENT_VERSION }}
          LATEST_VERSION: ${{ steps.check-version.outputs.LATEST_VERSION }}
        run: |
          git fetch --all
          if git ls-remote --exit-code --heads origin "$BRANCH_NAME"; then
            echo "Branch '$BRANCH_NAME' already exists."
            echo "BRANCH_EXISTS=true" >> "$GITHUB_OUTPUT"
          else
            echo "Branch '$BRANCH_NAME' does not exist."
            echo "BRANCH_EXISTS=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Perform upgrade
        id: perform-upgrade
        if: steps.check-branch.outputs.BRANCH_EXISTS == 'false'
        env:
          BRANCH_NAME: ${{ steps.check-version.outputs.BRANCH_NAME }}
          CURRENT_VERSION: ${{ steps.check-version.outputs.CURRENT_VERSION }}
          LATEST_VERSION: ${{ steps.check-version.outputs.LATEST_VERSION }}
          LATEST_MAJOR_VERSION: ${{ steps.check-version.outputs.LATEST_MAJOR_VERSION }}
        run: |
          git checkout -b "$BRANCH_NAME"
          npm run ng -- update @angular/core@"$LATEST_MAJOR_VERSION" @angular/cli@"$LATEST_MAJOR_VERSION" @angular/material@"$LATEST_MAJOR_VERSION" angular-eslint@"$LATEST_MAJOR_VERSION"
          git config --global user.name "Matthew Lonis"
          git config --global user.email "mattlonis@gmail.com"
          git add .
          git commit -m "Upgrade $DEPENDENCY_NAME from $CURRENT_VERSION to $LATEST_VERSION"
          git push -u origin "$BRANCH_NAME"
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Pull Request
        if: steps.perform-upgrade.conclusion == 'success'
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          LATEST_MAJOR_VERSION: ${{ steps.check-version.outputs.LATEST_MAJOR_VERSION }}
        run: |
          default_branch=$(gh repo view --json defaultBranchRef -q ".defaultBranchRef.name")
          gh pr create --base "$default_branch" --title "Upgrade to Angular to v$LATEST_MAJOR_VERSION" --body "Upgrade to Angular to v$LATEST_MAJOR_VERSION"
